Add applet to transfer CMV12K sensor data to DRAM
apertus-open-source-cinema/naps pull request #28
Opened 2021-08-11 01:41 UTC by tpwrules

Adds an applet to receive test data from the CMV12K sensor and store it in the main DRAM. Remapping is not implemented yet.

To do:

- [ ] Improve read speed (4-6MB/s, but sometimes 70MB/s)
- [ ] Fix `DramPacketRingbufferStreamWriter` (PR #24 broke it)
- [ ] Possibly validate pattern after transfer
- [ ] Possibly add HDMI output

2021-08-12 14:13 UTC, rroohhh requested changes
Just some preliminary notes, Ill take a deeper look later

2021-08-12 21:00 UTC, tpwrules commented on naps/cores/dram_packet_ringbuffer/cpu_if.py
> +        os.system(f"dd if=/dev/mem bs=4096 skip={base} count={length} iflag=skip_bytes,count_bytes of='{filename}'")
I think that would be nice too. Should we use `DevMemAccessor`, or just mmap /dev/mem directly? The downside would be that `DevMemAccessor` can only read one word at a time.

2021-08-12 21:01 UTC, tpwrules commented on naps/cores/dram_packet_ringbuffer/cpu_if.py
> +        m.d.sync += self.current_write_buffer.eq(writer.current_write_buffer)
To improve timing. It should not affect correctness I don't think.

2021-08-16 15:56 UTC, rroohhh commented on naps/cores/dram_packet_ringbuffer/cpu_if.py
> +        os.system(f"dd if=/dev/mem bs=4096 skip={base} count={length} iflag=skip_bytes,count_bytes of='{filename}'")
I think just mmap /dev/mem directly first, there are some changes to `DevMemAccessor` in the pipe, that will allow to read a arbitrary number of words at once, so we can switch to that when its ready.

2021-08-16 23:16 UTC, rroohhh approved these changes
Nice work!

2021-08-16 23:16 UTC, merged